### ISSUE TITLE
Azure OpenAI API key support

### ISSUE THREAD

**Issue by zjx1277** [om-ai-lab/OmAgent#1]
How to use Azure OpenAI keys in this repo?

**Comment by panregedit** [comment]
One approach involves directing the Azure API via the One API project (https://github.com/songquanpeng/one-api), enabling access to an API endpoint compatible with OpenAI integration. Alternatively, some adjustments within the code are necessary at the points where OpenAI is invoked. The OpenAI package encompasses an AzureOpenAI class designed for interfacing with Azure services.

**Comment by XeonHis** [comment]
Also, you can use the config template as follows with our implemented AzureGPTLLM
```
{
    "name": "AzureGPTLLM",
    "model_id": "your deployment model id in azure dashboard",
    "api_key": "your azure openai api key",
    "endpoint": "your custom azure openai endpoint",
    "api_version": "2024-02-15-preview", # same to api_version in azure dashboard is better, default is 2024-02-15-preview
    "temperature": 0,
    "vision": true,
    "response_format": "json_object or text"
  }
```

**Comment by zjx1277** [comment]
> Collaborator
> ###

Understood, Much appreciate!
