### ISSUE TITLE
Can you understand the spatial location in the video and realize AR navigation? For example, there is a video in the knowledge base that is a building, and then I upload a picture of the building location. He can determine where the location is and where to go and how to go

### ISSUE THREAD

**Issue by libai-lab** [om-ai-lab/OmAgent#10]
Can you understand the spatial location in the video and realize AR navigation? For example, there is a video in the knowledge base that is a building, and then I upload a picture of the building location. He can determine where the location is and where to go and how to go

**Comment by panregedit** [comment]
OmAgent currently only supports plain text query input, so it cannot complete the task you described. By modifying the indexing method of the video and introducing a multimodal encoder (such as BGE-visualized), a similar effect might be achieved.
