### ISSUE TITLE
大语言模型必须用openai的吗？

### ISSUE THREAD

**Issue by banchengyansha18** [om-ai-lab/OmAgent#11]
大语言模型必须用openai的吗？我怎么把它换成其他模型，报错                                                                                                                                   File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1017, in _request
   raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

**Comment by panregedit** [comment]
你可以使用其他大语言模型服务来代替openai gpt，只要接口格式和gpt相同即可。在workflows/video_understanding/config.yml 文件中修改custom_openai_endpoint字段来指向你希望使用的大模型接口地址。
你可以使用[one-api](https://github.com/songquanpeng/one-api)来对大模型接口进行转发，从而保证接口格式和gpt兼容

**Comment by yubo200526** [comment]
> 大语言模型必须用openai的吗？我怎么把它换成其他模型，报错 File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1017, in _request raise APIConnectionError(request=request) from err openai.APIConnectionError: Connection error.

您好，我在尝试该项目代码中对openai的api上传图片加文字或者audio时会遇到同样的错，还发现openai的api上传图片需要网址，代码中处理成base64编码格式就会遇到上述报错。

**Comment by panregedit** [comment]
> > 大语言模型必须用openai的吗？我怎么把它换成其他模型，报错 File "/usr/local/lib/python3.10/site-packages/openai/_base_client.py", line 1017, in _request raise APIConnectionError(request=request) from err openai.APIConnectionError: Connection error.
> 
> 您好，我在尝试该项目代码中对openai的api上传图片加文字或者audio时会遇到同样的错，还发现openai的api上传图片需要网址，代码中处理成base64编码格式就会遇到上述报错。

如果您使用非官方地址的GPT，首先请检查LLM地址是否已经被正确设置。如果地址已经被正确设置，请提供更详细的信息以便我可以帮助您寻找问题。
