### ISSUE TITLE
 Configuration issues

### ISSUE THREAD

**Issue by gaostar123** [om-ai-lab/OmAgent#3]
I still don’t quite understand how config.yaml is configured. Can the configuration process be more detailed? thank you very much

**Comment by N1ana7mi** [comment]
if u use the command the author provided:  cd workflows/general && vim config.yaml
when you enter vim, you can just enter these, and then save them
```ruby
custom_openai_endpoint: "your base"
custom_openai_key: "your key"
bing_api_key: "your key"
```
or u can just create "config.yaml"  in the correct path and enter the info

**Comment by panregedit** [comment]
I added sample config files, please checkout:
workflows/general/config.yml
workflows/video_understanding/config.yml
