### ISSUE TITLE
pydantic stops video_understanding task

### ISSUE THREAD

**Issue by brianliu2** [om-ai-lab/OmAgent#5]
my pydantic version is 2.2, and when run the video_understanding task, it shows the warning and terminates the run.

```
UserWarning: Field "model_id" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
[1]    63213 illegal hardware instruction  python run.py
```

I can see solutions such as `from pydantic import ConfigDict` is added in `omagent_core/llm/gpt.py` and 

```
class Config:

        protected_namespaces = ()
        extra = "allow"
```
is added in `omagent_core/llm/openai_gpt.py`.

But it doesn't resolve the issue.

**Comment by panregedit** [comment]
It is caused by the OVD tool in 'engine/tools/ovd_tool.py'. I fixed it in the most recent commit.
