### ISSUE TITLE
Bing's api key, used for web search

### ISSUE THREAD

**Issue by YanhuiS** [om-ai-lab/OmAgent#7]
请问BING API key的申请有教程吗？

**Comment by YanhuiS** [comment]
另外，你正文中写的是“ovd 工具 API 地址。如果使用 OmDet，地址应该是http://host:8000/inf_predict”，我看ovd API 结果是http://localhost:8000/？

**Comment by panregedit** [comment]
申请 bing api key 你需要先申请一个微软Azure平台账号，然后根据微软的教程进行创建。
“http://host:8000/inf_predict”这里的“host”指的是你部署服务的服务器ip地址，如果你的omdet和omagent是部署在同一台机器上，那么可以使用localhost来访问

**Comment by YanhuiS** [comment]
好的好的，感谢您的回复。
