### ISSUE TITLE
在哪里可以看到data/face_db呀？

### ISSUE THREAD

**Issue by YanhuiS** [om-ai-lab/OmAgent#8]

**Comment by panregedit** [comment]
你需要在 data/face_db 目录创建自己的人脸库。只需要将同一个人的图片放在一个文件夹中，文件夹名称为人员的人名或ID。

**Comment by YanhuiS** [comment]
感谢你的回复，构建face_db需要将视频理解数据集中每一个人检测到的人脸都存下来，然后用名字命名嘛？人名是怎么获得的呀？有没有构建好的share一下呀？

**Comment by panregedit** [comment]
你可以使用你需要的人物来构建自己的数据集，例如要处理的视频是电影，那么你可以吧对应的演员存在人脸底库里。名字可以用人名或者代号或者其他id，这个名字会在识别后传递给大模型。

**Comment by YanhuiS** [comment]
好的好的，感谢您的回复。
