### ISSUE TITLE
Milvus配置

### ISSUE THREAD

**Issue by yubo200526** [om-ai-lab/OmAgent#97]
请问下使用video_understanding模块必须配置Milvus的docker嘛

**Comment by panregedit** [comment]
哈喽，用Docker部署Milvus服务并不是必须的。新版的Milvus支持了轻量版的Milvus Lite，通过在本地存储一个.db文件实现向量存储的搜索功能。OmAgent默认支持使用Milvus Lite，你不需要部署或者配置Milvus服务。
不过如果你需要更好的性能，还是推荐部署Docker版本。

**Comment by yubo200526** [comment]
因为我在使用Milvus服务时，配置STORAGE_NAME为‘default’，貌似该collection的dim默认为512，即使我配置DIM为3072，仍然会报错<MilvusException: (code=2000, message=vector dimension mismatch, expected vector size(byte) 512, actual 12288.: segcore error)>；因此我想要配置STORAGE_NAME为其他字段时发现连接MilvusClient比较卡顿，好像不太支持其他函数例如get方法，会得到报错 <MilvusException: (code=100, message=Can not find test's schema: collection not found)>，请您帮我解答一下这个困惑，我该如何正确配置STORAGE_NAME和DIM？

**Comment by panregedit** [comment]
MilvusLTM 包含一个 dim 属性，通过设置这个属性可以设置存储的向量维度。当你compile container之后会得到一个container.yaml配置文件，你可以在配置文件中找到MilvusLTM以及dim属性，修改这个属性值，并使用container.from_config重新加载，就可以成功修改dim配置。LTM相关的例子可以参考 examples/step4_outfit_with_ltm 示例，以及 docs/examples/outfit_with_ltm.md 文档。

**Comment by yubo200526** [comment]
你好，我不是很理解您在VideoQA组件的这部分代码，我认为并且跑代码发现related_information= self.ltm.get_by_vector是对于milvus向量库的问题相似搜索，并不能返回scenes的surmmary的相关信息；并且您貌似没有地方用到Video.scenes，我认为这个中的内容是对于scenes的总结；
![1732604291195](https://github.com/user-attachments/assets/dc8854a2-1795-41ad-a000-c82060384c67)

**Comment by yubo200526** [comment]
> 你好，我不是很理解您在VideoQA组件的这部分代码，我认为并且跑代码发现related_information= self.ltm.get_by_vector是对于milvus向量库的问题相似搜索，并不能返回scenes的surmmary的相关信息；并且您貌似没有地方用到Video.scenes，我认为这个中的内容是对于scenes的总结； ![1732604291195](https://private-user-images.githubusercontent.com/97269932/389830190-dc8854a2-1795-41ad-a000-c82060384c67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDk3NzUsIm5iZiI6MTczMjYwOTQ3NSwicGF0aCI6Ii85NzI2OTkzMi8zODk4MzAxOTAtZGM4ODU0YTItMTc5NS00MWFkLWEwMDAtYzgyMDYwMzg0YzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA4MjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MDdkMjc4MzMzNjdhY2NlMjE5NTE1NzNkNDE1Mjc0NTEwNTAwZGM5NjZkMWQzZGZkM2JiZTMwYTg4NTYyOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.T5jyAkUKN18dzishw9jqwaN--VOl_ZRURKNJzfch-HI)

抱歉这是由于我的问题没有找到相关性的内容，导致返回了空集合；但我注意到代码在这里没有做保护
